/**
 * Symbol-reference persistence (schema v14, Phase 101 — Task 629).
 *
 * A `ref` row says: symbol S (in `source_file` of this repo) mentions, inside
 * its byte span, a name that the file imported from `target_file`, where that
 * name is symbol T. Derived from three stored facts — the import record with
 * its names, the target file's symbol table, the source symbol's span over the
 * file bytes — never from a fresh parse (design note §5). Every row is
 * `confidence: 'lexical'`: a word-boundary text match, so a shadowed local, a
 * string or a comment can produce a false positive by construction.
 *
 * Kept OUT of `dep_edges` so the file-level readers stay byte-identical (P1)
 * and the far larger ref volume never enters their index scans. Local rows
 * store `target_repo_id = ''`; the API exposes `targetRepoId: null` for them,
 * matching `DepEdge`.
 */
import type Database from 'better-sqlite3';
import type { SymbolRecord, SymbolKind } from '../types.js';
import { StorageError } from '../errors.js';

// ─── Types ────────────────────────────────────────────────────────────────────

export type RefConfidence = 'lexical';

export interface SymbolRef {
  repoId: string;
  sourceFile: string;
  sourceSymbolId: string;
  targetFile: string;
  targetSymbolId: string;
  /** Linked index that owns the target; null = this index. */
  targetRepoId: string | null;
  /** The bare name that matched. */
  name: string;
  confidence: RefConfidence;
  /** Occurrences of the name inside the source symbol's span. */
  refCount: number;
}

interface RefRow {
  repo_id: string;
  source_file: string;
  source_symbol_id: string;
  target_file: string;
  target_symbol_id: string;
  target_repo_id: string;
  name: string;
  confidence: string;
  ref_count: number;
}

interface DbSymbolRow {
  id: string;
  name: string;
  kind: string;
  file_path: string;
  start_byte: number;
  end_byte: number;
  signature: string;
  summary: string;
  framework_meta: string | null;
}

const LOCAL = '';

function rowToRef(r: RefRow): SymbolRef {
  return {
    repoId: r.repo_id,
    sourceFile: r.source_file,
    sourceSymbolId: r.source_symbol_id,
    targetFile: r.target_file,
    targetSymbolId: r.target_symbol_id,
    targetRepoId: r.target_repo_id === LOCAL ? null : r.target_repo_id,
    name: r.name,
    confidence: r.confidence as RefConfidence,
    refCount: r.ref_count,
  };
}

function rowToSymbol(row: DbSymbolRow): SymbolRecord {
  return {
    id: row.id,
    name: row.name,
    kind: row.kind as SymbolKind,
    filePath: row.file_path,
    startByte: row.start_byte,
    endByte: row.end_byte,
    signature: row.signature,
    summary: row.summary,
    frameworkMeta: row.framework_meta
      ? (JSON.parse(row.framework_meta) as Record<string, unknown>)
      : undefined,
  };
}

// ─── Writes ───────────────────────────────────────────────────────────────────

/**
 * Insert refs. A duplicate key (same source symbol → same target symbol) adds
 * its count rather than failing — the builder aggregates first, but a
 * re-export hop can legitimately reach one target through two names.
 */
export function insertSymbolRefs(db: Database.Database, refs: SymbolRef[]): void {
  if (refs.length === 0) return;
  const stmt = db.prepare(`
    INSERT INTO symbol_refs
      (repo_id, source_file, source_symbol_id, target_file, target_symbol_id, target_repo_id, name, confidence, ref_count)
    VALUES
      (@repoId, @sourceFile, @sourceSymbolId, @targetFile, @targetSymbolId, @targetRepoId, @name, @confidence, @refCount)
    ON CONFLICT (repo_id, source_symbol_id, target_repo_id, target_symbol_id) DO UPDATE SET
      ref_count = ref_count + excluded.ref_count
  `);
  const run = db.transaction((rows: SymbolRef[]) => {
    for (const r of rows) {
      try {
        stmt.run({
          repoId: r.repoId,
          sourceFile: r.sourceFile,
          sourceSymbolId: r.sourceSymbolId,
          targetFile: r.targetFile,
          targetSymbolId: r.targetSymbolId,
          targetRepoId: r.targetRepoId ?? LOCAL,
          name: r.name,
          confidence: r.confidence,
          refCount: r.refCount,
        });
      } catch (err) {
        throw new StorageError(
          `Failed to insert symbol ref ${r.sourceSymbolId} → ${r.targetSymbolId}`,
          'insertSymbolRefs',
          err,
        );
      }
    }
  });
  run(refs);
}

/** Reprocess path: a file's OUTGOING refs are regenerated by its own rebuild. */
export function deleteSymbolRefsBySource(
  db: Database.Database,
  repoId: string,
  sourceFile: string,
): void {
  db.prepare('DELETE FROM symbol_refs WHERE repo_id = ? AND source_file = ?').run(repoId, sourceFile);
}

/**
 * Deletion path: the file is gone from disk, so both its outgoing refs and
 * the LOCAL refs pointing at it dangle. Cross rows aimed at a same-named
 * file in another index are left alone (Phase 99 rule).
 */
export function deleteSymbolRefsByFile(
  db: Database.Database,
  repoId: string,
  filePath: string,
): void {
  db.prepare(
    `DELETE FROM symbol_refs WHERE repo_id = ? AND (source_file = ? OR (target_file = ? AND target_repo_id = ''))`,
  ).run(repoId, filePath, filePath);
}

/**
 * Target-side hygiene (design note §2.5): after `targetFile` was re-parsed,
 * drop local refs whose target symbol id no longer exists in it (a rename or
 * kind change produced a new id). Returns the number of rows removed.
 */
export function deleteDanglingSymbolRefsInto(
  db: Database.Database,
  repoId: string,
  targetFile: string,
): number {
  const res = db
    .prepare(
      `DELETE FROM symbol_refs
       WHERE repo_id = ? AND target_file = ? AND target_repo_id = ''
         AND target_symbol_id NOT IN (SELECT id FROM symbols WHERE repo_id = ? AND file_path = ?)`,
    )
    .run(repoId, targetFile, repoId, targetFile);
  return res.changes;
}

/** Remove every ref of a repo (whole-graph rebuild). */
export function deleteAllSymbolRefs(db: Database.Database, repoId: string): void {
  db.prepare('DELETE FROM symbol_refs WHERE repo_id = ?').run(repoId);
}

// ─── Reads ────────────────────────────────────────────────────────────────────

/** How many refs this repo stores (0 → readers fall back to the file answer). */
export function countSymbolRefs(db: Database.Database, repoId: string): number {
  return (
    db
      .prepare<[string], { n: number }>('SELECT COUNT(*) AS n FROM symbol_refs WHERE repo_id = ?')
      .get(repoId)?.n ?? 0
  );
}

/** Symbols that `symbolId` references (forward, one hop; local AND cross rows). */
export function getForwardRefs(
  db: Database.Database,
  repoId: string,
  symbolId: string,
): SymbolRef[] {
  return db
    .prepare<[string, string], RefRow>(
      'SELECT * FROM symbol_refs WHERE repo_id = ? AND source_symbol_id = ? ORDER BY target_file, target_symbol_id',
    )
    .all(repoId, symbolId)
    .map(rowToRef);
}

/** Symbols of THIS index that reference the local symbol `symbolId` (reverse, one hop). */
export function getReverseRefs(
  db: Database.Database,
  repoId: string,
  symbolId: string,
): SymbolRef[] {
  return db
    .prepare<[string, string], RefRow>(
      `SELECT * FROM symbol_refs WHERE repo_id = ? AND target_repo_id = '' AND target_symbol_id = ?
       ORDER BY source_file, source_symbol_id`,
    )
    .all(repoId, symbolId)
    .map(rowToRef);
}

/**
 * Phase-99 seam query: refs stored in `db`'s repo `repoId` whose target is
 * symbol `symbolId` inside the LINKED index `targetRepoId`. Asked of every
 * other workspace member during a reverse walk.
 */
export function getCrossReverseRefs(
  db: Database.Database,
  repoId: string,
  targetRepoId: string,
  symbolId: string,
): SymbolRef[] {
  return db
    .prepare<[string, string, string], RefRow>(
      `SELECT * FROM symbol_refs WHERE repo_id = ? AND target_repo_id = ? AND target_symbol_id = ?
       ORDER BY source_file, source_symbol_id`,
    )
    .all(repoId, targetRepoId, symbolId)
    .map(rowToRef);
}

/** Every ref whose source is in `sourceFile` (the file's outgoing refs). */
export function getRefsBySourceFile(
  db: Database.Database,
  repoId: string,
  sourceFile: string,
): SymbolRef[] {
  return db
    .prepare<[string, string], RefRow>(
      'SELECT * FROM symbol_refs WHERE repo_id = ? AND source_file = ? ORDER BY source_symbol_id, target_symbol_id',
    )
    .all(repoId, sourceFile)
    .map(rowToRef);
}

/** Every ref stored in this repo whose target lives in a linked index. */
export function getCrossSymbolRefs(db: Database.Database, repoId: string): SymbolRef[] {
  return db
    .prepare<[string], RefRow>(
      `SELECT * FROM symbol_refs WHERE repo_id = ? AND target_repo_id <> '' ORDER BY source_file, source_symbol_id`,
    )
    .all(repoId)
    .map(rowToRef);
}

/**
 * Per target symbol (local targets only): how many DISTINCT source symbols
 * reference it — the symbol-level afferent count `get_symbol_risk` blends as
 * centrality when a repo has refs.
 */
export function getAfferentSymbolCounts(db: Database.Database, repoId: string): Map<string, number> {
  const rows = db
    .prepare<[string], { target_symbol_id: string; n: number }>(
      `SELECT target_symbol_id, COUNT(DISTINCT source_symbol_id) AS n
       FROM symbol_refs WHERE repo_id = ? AND target_repo_id = '' GROUP BY target_symbol_id`,
    )
    .all(repoId);
  const out = new Map<string, number>();
  for (const r of rows) out.set(r.target_symbol_id, r.n);
  return out;
}

/**
 * Phase-99 seam: per target symbol of index `targetRepoId`, how many distinct
 * symbols of `db`'s repo `repoId` reference it (centrality across the seam).
 */
export function getCrossAfferentSymbolCounts(
  db: Database.Database,
  repoId: string,
  targetRepoId: string,
): Map<string, number> {
  const rows = db
    .prepare<[string, string], { target_symbol_id: string; n: number }>(
      `SELECT target_symbol_id, COUNT(DISTINCT source_symbol_id) AS n
       FROM symbol_refs WHERE repo_id = ? AND target_repo_id = ? GROUP BY target_symbol_id`,
    )
    .all(repoId, targetRepoId);
  const out = new Map<string, number>();
  for (const r of rows) out.set(r.target_symbol_id, r.n);
  return out;
}

/**
 * Source symbols of the reverse refs, materialised (the reverse walk wants
 * records, not ids). Joins `symbols` so a stale row whose source symbol was
 * re-keyed is silently absent rather than a dangling id.
 */
export function getReferencingSymbols(
  db: Database.Database,
  repoId: string,
  symbolId: string,
): Array<{ symbol: SymbolRecord; refCount: number; name: string }> {
  const rows = db
    .prepare<[string, string], DbSymbolRow & { ref_count: number; ref_name: string }>(
      `SELECT s.id, s.name, s.kind, s.file_path, s.start_byte, s.end_byte, s.signature, s.summary, s.framework_meta,
              r.ref_count, r.name AS ref_name
       FROM symbol_refs r
       JOIN symbols s ON s.repo_id = r.repo_id AND s.id = r.source_symbol_id
       WHERE r.repo_id = ? AND r.target_repo_id = '' AND r.target_symbol_id = ?
       ORDER BY s.file_path, s.start_byte`,
    )
    .all(repoId, symbolId);
  return rows.map((r) => ({ symbol: rowToSymbol(r), refCount: r.ref_count, name: r.ref_name }));
}
